### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by Sedrowow** [Ilya246/assistBots#1]
expected behaviour:
while starting no errors or crash

actual behaviour:
crash with error:
`
[02-07-2023 16:29:44] [E] java.lang.NoSuchMethodError: void arc.struct.Seq.add(java.lang.Object)
	at assistBotsMod.assistBotsMod.balancePlayers(assistBotsMod.java:106)
	at assistBotsMod.assistBotsMod.lambda$init$0(assistBotsMod.java:64)
	at arc.util.Timer$2.run(Timer.java:101)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:81)
	at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
`

**Comment by Ilya246** [comment]
this is caused by it being compiled for a build of mindustry that's too old, fixed this a while ago, closing
